### ISSUE TITLE
Suggestion: Show wallpaper based on Time of day

### ISSUE THREAD

**Issue by bastianilso** [maoschanz/dynamic-wallpaper-editor#15]
Hello,

I have a few wallpaper collections which have a "-morning.jpg" "-afternoon.jpg", "-evening.jpg" and "-night.jpg". How can I use dynamic wallpaper editor to make sure that each of them only show in those specific time windows? And could we possibly have a simpler user interface to adjust wallpapers to something like that?

**Comment by maoschanz** [comment]
It's actually a complex question, because things like seasons, time zone and summer time mean there isn't an universal setting for doing this (for example, an old french idiom says "looking for noon at 14 o'clock" to mean "uselessly complicate an issue"; nowadays we are in Poland's time zone and we use summer time, so the sun _actually_ reaches the zenith at 14 o'clock half of the year).

For now, the total time in the status bar is converted in hours so you know if the total is 24h. I think i'll use 7am as a default start time (not perfect but still better than midnight), and maybe provide an option to change time units?

**Comment by maoschanz** [comment]
i set 7am as the default start hour, and i tried this: https://youtu.be/8o9gW3ObzvA does it fix the issue ? of course the algorithm automatically setting the durations is stupid but can be improved in the future

**Comment by bastianilso** [comment]
Thank you for looking into this!

I am still a bit confused as to how to set the wallpaper to match the correct day of time. Maybe if we in the UI could choose the time (say begin this from "7:00 AM", then begin this from "12:00 AM" etc).. :)

**Comment by maoschanz** [comment]
i'm closing this, i think it's clear enough now
![](https://raw.githubusercontent.com/maoschanz/dynamic-wallpaper-editor/master/help/C/figures/screenshot.png)
