### ISSUE TITLE
dconf-path is broken after (session) restart

### ISSUE THREAD

**Issue by F3l1XQu1ll** [maoschanz/dynamic-wallpaper-editor#24]
After session restart (reboot or logout and relogin), the wallpaper path in dconf is broken.
The path to `/run/user/1000/doc/…` is temporary and changes in every new session.
![Bildschirmfoto von 2019-07-29 11-30-24](https://user-images.githubusercontent.com/39009640/62037967-1b061c80-b1f5-11e9-8ad1-2cf699bc4b02.png)
_The number after …/doc/… changes everytime_

@maoschanz I have seen you mentioned this allready in Todo.md.
I'll see if I can fix it my self …

**Comment by maoschanz** [comment]
I've mentionned it but not fixed it because it looks like an issue specific to Wayland. But I know how to fix it: by breaking the sandbox and only allowing wallpapers from /home/xxx/

It's not an acceptable solution in my opinion (and in flathub's admins opinion), so i stay with Xorg and /run/user/1000

**Comment by F3l1XQu1ll** [comment]
I was looking around in the dir and found out that the …/doc/… dir is gone after session restart …
Maybe because of https://github.com/flatpak/xdg-desktop-portal/issues/318
It seems to be a Flatpak issue

**Comment by F3l1XQu1ll** [comment]
I have my own solution to fix it (without breaking the sandbox): use GLib.get_user_data_dir() to store the xml file. This would break the current load and save mechanism but the data is persistent.

**Comment by maoschanz** [comment]
No, don't do such things, let the app like it's now, people can use Xorg to have a persistent /run/user/1000 or they can set their wallpaper/lockscreen with Tweaks, if you really want this bug to disappear i prefer destroying entirely this feature rather than breaking the open/save mechanism

**Comment by F3l1XQu1ll** [comment]
What feaure exactly do you want to distroy?
What I meant is that the .xml file is allways saved in a hardcoded dir. (Which is per default ~/.local/share/… or when using Flatpak ~/.var/app/com.github.maoschanz.DynamicWallpaperEditor/data/…) The File can be loaded from there to be modified. (Of curse, users could want multible "standart" Wallpapers but this would also possible)

But, I understand it's your app and this would chage mutch of it's functionality – My problem is that I have Wayland preinstalled don't want to uninstall it (I do not know much about this and don't want to break sth.)

**Comment by maoschanz** [comment]
This is an editor, you have XML files somewhere, you open them, you edit them, you save them. This is the core of this app.

Setting a file as a wallpaper is a bonus, no one need this app to do this: Tweaks already does it, even the native system settings can do it under a few conditions.

The possible solutions regarding the "set as wallpaper" action are:

- a "home:rw" hole in the sandbox (refused by flathub)
- a feature working only on Xorg because with Wayland the /run/user/ directory is reset
- removing this feature
- having 2 workflows in the same app (*open (through the portal) -> edit -> save* and *open (using the existing read-only hole in the sandbox) -> preview -> apply*)

The last one is not very elegant concerning the ergonomy and the UI design, but it would make the code more clear, i'll probably do that

**Comment by F3l1XQu1ll** [comment]
I allso think this is the best way. Maybe we can put the two things together: you are able to open, modifiy and save the Files as now and just when you set the file as wallpaper, a copy gets stored at ~/.var/app/ etc. This would keep functionality as it is and would save the problem. I was wrong when I sayed it would break the load/save mechanism. The mentioned dir is flatpak "native" and you don't need to dig a new hole in the sandbox. If you want, I can do this and make a pull request when ready.

**Comment by maoschanz** [comment]
Too late i already began the 2 workflows idea, i'll use it to test some cool widgets

**Comment by F3l1XQu1ll** [comment]
No problem; it would fit anyway. I'll make a pull request to demonstrate it.

**Comment by maoschanz** [comment]
so all this time i was trying to check if the desktop needed a path or an URI while both work fine with any desktop...

**Comment by F3l1XQu1ll** [comment]
Acording to dconf, only URI (file://…) is allowed! I have seen this too late. The wallpaper won't change after time if this "prefix" is missing.

**Comment by maoschanz** [comment]
No, it looks like it really works with a path, the only issue with your strategy is that the wallpaper now always have the same name, so the DE isn't correctly notified when it changes.

But i think it's easy to fix, for example if the current wallpaper is already "wallpaper.xml" it could use a file named "wallpaper0.xml", it's 3 lines to add

**Comment by F3l1XQu1ll** [comment]
I have made a pull request to fix this and the issue, that lockscreen and desktop wallpaper overwrite each other.

**Comment by maoschanz** [comment]
what name should i add to the about dialog? F3l1XQu1ll, Felix, something else?

**Comment by F3l1XQu1ll** [comment]
Felix Quill, please :slightly_smiling_face:

**Comment by maoschanz** [comment]
i close this one too
