### ISSUE TITLE
Transition in ms

### ISSUE THREAD

**Issue by ZicPL** [maoschanz/dynamic-wallpaper-editor#32]
Your application is awesome. Can you set the transition to milliseconds instead of seconds? I would like the wallpapers to change quickly as the gif works. I changed the transition in the .xml file. Unfortunately, that didn't help..

**Comment by maoschanz** [comment]
>I changed the transition in the .xml file. Unfortunately, that didn't help..

so it doesn't work.

Why would i make the UI unreadable to humans if the expected result doesn't work?

**Comment by ZicPL** [comment]
I was hoping you'd take me seriously.. By writing above message, I meant the implementation of time intervals in your code. Here I see what units you use:
```
def get_start_time(self):
		h = self.hour_spinbtn.get_value_as_int()
		m = self.minute_spinbtn.get_value_as_int()
		s = self.second_spinbtn.get_value_as_int()
		return [h, m, s]
```
So the smallest unit of time is Second. Therefore in your application, time for displaying walls cannot be less than 1 second:
[Image on imgur](https://imgur.com/a/wZLRa5x)
Could you consider adding new unit? in milliseconds? I am not the best at programming so I opened a new issue.

**Comment by maoschanz** [comment]
But this app is just a sweet GUI reading/writing some correct XML with the right tags. Then, using an XML file as wallpaper is a native feature implemented by your DE, which i don't maintain.

If editing manually to use a float doesn't help\*, it means the DE wants integers\** (and it makes sense they don't support that, changing the wallpaper several time per second would require a big amount of resources). This feature exists natively to provide something like the macOS Mojave's dynamic wallaper, or like a classic Windows XP's slideshow with holiday photos like boomers enjoy. Setting a video or a GIF as your wallpaper is a quite different technical challenge

----

\*because of flatpak technical limitations, the path set in dconf isn't the file you edit, but a copy stored in a hidden folder. To be **sure** the DE doesn't support it you should set the manually edited file as your wallpaper from Tweaks. I know nothing under a second is taken into account by GNOME Shell, maybe other DE are different?

\** i know the file has floats ending with `.0` but since GNOME Shell can't manage durations under `1.0` i assume it's converted to an integer somewhere

**Comment by ZicPL** [comment]
Your last sentence is what I'm looking for: "Setting a video or a GIF as your wallpaper is a quite different technical challenge". Someone can said that I was desperate to use a wallpaper changer as video background.. and he/she will be right. I've tried everything:
- Komorebi (git: cheesecakeufo/komorebi) - doesn't work with wayland.
- Oguri/sway (vilhalmer/oguri)- doesn't work with Mutter (Gnome composer), [link](https://github.com/vilhalmer/oguri/issues/17),
- hundreds of Gnome extensions.
In this case "impassable wall" is Desktop Environments
I haven't more ideas what to do. I don't want to change Wayland to x11, but I can't see other way.

**Comment by maoschanz** [comment]
ah yes, sadly Wayland makes us very dependant of GNOME Shell devs' decisions, and i guess people would throw tomatoes at them if they ever do something as resource-hungry as this feature

good luck
